### ISSUE TITLE
can't new WebHook()

### ISSUE THREAD

**Issue by dfghj44444** [jerrybendy/coding-webhook-php#7]
i am the first time using composer,and I write the example coreectly.is there something to about code should I do?
I doubt" use Jerrybendy\Coding\Webhook;" does not work at all.

**Comment by jerrybendy** [comment]
Can you paste your code? and which version of you PHP?

**Comment by dfghj44444** [comment]
now I know WebHook can be new,something wrong,caused by exec be disabled for default.but now comes new issue:Undefined class constant Webhook::EVENT_TYPE_PUSH.
I'm in cents 7,php5.6.19

```
<?php
ini_set('display_errors', 'On');
error_reporting(E_ALL);
require('vendor/autoload.php');

use Jerrybendy\Coding\Webhook;

/*
 * 在这里定义你的 token , 可以为空
 */
define('TOKEN', 'xlzh');

$webHook = new Webhook(TOKEN);

$webHook
    ->on(Webhook::EVENT_TYPE_PUSH, function ($data) {

        if ($data->ref === 'refs/heads/master') {
            exec('git pull');
        }
    })
    ->run();  // 最后一定要调用一次 run() 函数
?>
```

**Comment by jerrybendy** [comment]
Oh, I'm sorry , the package version in composer is not the latest!

I have changed the name `MESSAGE_TYPE_PUSH` to `EVENT_TYPE_PUSH`, but forget to make tag for composer.  I have fixed this error now. You can use `"jerrybendy/coding-webhook-php": "^0.2.1"` to instead `v0.2.0` to get this fix. thanks !

``` json
    "require": {
        "jerrybendy/coding-webhook-php": "^0.2.1"
    },
```

**Comment by jerrybendy** [comment]
Of cause, if you don't want to update composer, you can use `MESSAGE_TYPE_***` to instead of `EVENT_TYPE_***`. It will work well  😁
